from solvers.SolverBaseParams import *
from solvers.SolverBase import *
from solvers.BatchSolver import *
from solvers.WholeSolver import *
from solvers.MLPSolParams import MLPSolParams
from solvers.TorchVisionSolParams import TorchVisionSolParams
from solvers.RA_GCNSolParams import *
from solvers.MA_GCNNSolParams import MA_GCNNSolParams
from solvers.DW_DGATSolParams import DW_DGATSolParams
from solvers.MV_GCNSolParams import MV_GCNSolParams
from solvers.GCNSolParams import GCNSolParams
from solvers.GATSolParams import GATSolParams
from solvers.GATv2SolParams import GATv2SolParams
from solvers.ChebNetIISolParams import ChebNetIISolParams
from solvers.HyLaNetSolParams import HyLaNetSolParams
from solvers.LG_GNNSolParams import LG_GNNSolParams
from solvers.NetworkGATSolParams import *
from solvers.NetworkGATv2SolParams import *
from solvers.GraphormerSolParams import *
from solvers.ChAdaViTSolParams import *
from solvers.SwinTransformerSolParams import *
from solvers.BrainNetCNNSolParams import *
from solvers.BrainNetTransformerSolParams import *
from solvers.GCN_MHSASolParams import *
from solvers.BrainGNNSolParams import *
from solvers.ViTSolParams import ViTSolParams
