from arguments.Arguments import *
from arguments.BDArguments import *
from arguments.TorchVisionArgs import *
from arguments.MLPArgs import *
from arguments.GCNArgs import *
from arguments.GATArgs import *
from arguments.ChebNetIIArgs import *
from arguments.MV_GCNArgs import *
from arguments.MA_GCNNArgs import *
from arguments.RA_GCNArgs import *
from arguments.DW_DGATArgs import *
from arguments.HyLaNetArgs import *
from arguments.LG_GNNArgs import *
from arguments.ContrastPoolNetArgs import *
from arguments.GraphormerArgs import *
from arguments.GATv2Args import *
from arguments.NetworkGATArgs import *
from arguments.NetworkGATv2Args import *
from arguments.ChAdaViTArgs import *
from arguments.SwinTransformerArgs import *
from arguments.BrainNetCNNArgs import *
from arguments.BrainNetTransformerArgs import *
from arguments.GCN_MHSAArgs import *
from arguments.BrainGNNArgs import *
from arguments.ViTArgs import *
